# Generated by Django 4.2.7 on 2026-04-17 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название локации')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='MFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(default='не определен', max_length=100, verbose_name='Номер основного средства')),
                ('model', models.CharField(max_length=100, verbose_name='Модель МФУ')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'МФУ',
                'verbose_name_plural': 'МФУ',
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, unique=True, verbose_name='Марка монитора')),
            ],
            options={
                'verbose_name': 'Монитор',
                'verbose_name_plural': 'Мониторы',
            },
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка телевизора')),
                ('size', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Диагональ (дюймы)')),
                ('asset_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер основного средства')),
                ('location', models.TextField(blank=True, null=True, verbose_name='Место расположения')),
            ],
            options={
                'verbose_name': 'Телевизор',
                'verbose_name_plural': 'Телевизоры',
            },
        ),
        migrations.CreateModel(
            name='UPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(default='не определен', max_length=100, verbose_name='Номер основного средства')),
                ('model', models.CharField(max_length=100, verbose_name='Модель ИБП')),
                ('battery_serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Серийный номер аккумулятора')),
                ('battery_replaced_at', models.DateField(blank=True, null=True, verbose_name='Дата замены аккумулятора')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'ИБП (бесперебойник)',
                'verbose_name_plural': 'ИБП (бесперебойники)',
            },
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='Место (кабинет/здание)')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('inactive', 'Неактивно'), ('maintenance', 'На обслуживании'), ('repair', 'Требует ремонта')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.location', verbose_name='Город/Локация')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee', verbose_name='Сотрудник')),
                ('mfp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mfp', verbose_name='МФУ')),
                ('ups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ups', verbose_name='Бесперебойник')),
            ],
            options={
                'verbose_name': 'Рабочее место',
                'verbose_name_plural': 'Рабочие места',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='ups_asset_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to_employees', to='api.ups', verbose_name='Номер основного средства бесперебойника'),
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(default='не определен', max_length=100, verbose_name='Номер основного средства')),
                ('system_unit', models.CharField(blank=True, max_length=200, null=True, verbose_name='Системный блок')),
                ('has_keyboard', models.BooleanField(default=False, verbose_name='Клавиатура')),
                ('has_mouse', models.BooleanField(default=False, verbose_name='Мышь')),
                ('needs_upgrade', models.BooleanField(default=False, verbose_name='Требует модернизации')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee', verbose_name='Закреплен за сотрудником')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department', verbose_name='Отдел')),
                ('monitors', models.ManyToManyField(blank=True, to='api.monitor', verbose_name='Мониторы')),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
            },
        ),
    ]
