# Generated by Django 4.2.7 on 2026-04-22 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ups',
            options={},
        ),
        migrations.RemoveField(
            model_name='ups',
            name='battery_replaced_at',
        ),
        migrations.RemoveField(
            model_name='ups',
            name='battery_serial_number',
        ),
        migrations.AddField(
            model_name='ups',
            name='replacement_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания замены'),
        ),
        migrations.AddField(
            model_name='ups',
            name='replacement_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала замены'),
        ),
        migrations.AddField(
            model_name='ups',
            name='replacement_ups',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='api.ups', verbose_name='Временная замена'),
        ),
        migrations.AddField(
            model_name='ups',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('repair', 'В ремонте'), ('replaced', 'Заменен временно')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='ups',
            name='asset_number',
            field=models.CharField(default='не определен', max_length=100, unique=True, verbose_name='Номер основного средства'),
        ),
        migrations.CreateModel(
            name='BatteryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_battery_serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Извлеченный аккумулятор (серийный номер)')),
                ('new_battery_serial', models.CharField(max_length=100, verbose_name='Установленный аккумулятор (серийный номер)')),
                ('replaced_at', models.DateField(auto_now_add=True, verbose_name='Дата замены')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к замене')),
                ('performed_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='Кто выполнил замену')),
                ('ups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_history', to='api.ups', verbose_name='ИБП')),
            ],
            options={
                'verbose_name': 'История замены АКБ',
                'verbose_name_plural': 'История замены АКБ',
                'ordering': ['-replaced_at'],
            },
        ),
    ]
