# Generated by Django 4.2.7 on 2026-04-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ups_options_remove_ups_battery_replaced_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ups',
            name='asset_number',
            field=models.CharField(default='не определен', max_length=100, verbose_name='Номер основного средства'),
        ),
    ]
