# Generated by Django 4.2.7 on 2026-04-22 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ups_asset_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ups',
            name='replacement_end_date',
        ),
        migrations.RemoveField(
            model_name='ups',
            name='replacement_start_date',
        ),
    ]
