# Generated by Django 4.2.7 on 2026-04-22 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_ups_replacement_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mfp',
            name='department',
        ),
    ]
