# Generated by Django 4.2.7 on 2026-04-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_mfp_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='department',
        ),
    ]
