# Generated by Django 4.2.7 on 2026-04-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_computer_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='computer_type',
            field=models.CharField(choices=[('desktop', '🖥️ Стационарный'), ('laptop', '💻 Ноутбук'), ('all-in-one', '🖥️ Моноблок')], default='desktop', max_length=20, verbose_name='Тип компьютера'),
        ),
        migrations.AddField(
            model_name='computer',
            name='service_status',
            field=models.CharField(choices=[('operational', '✅ В эксплуатации'), ('repair', '🔧 В ремонте'), ('upgrade', '⚡ На модернизации')], default='operational', max_length=20, verbose_name='Статус обслуживания'),
        ),
    ]
