# Generated by Django 4.2.7 on 2026-04-22 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_computer_computer_type_computer_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='computer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.computer', verbose_name='Компьютер'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='location',
            field=models.CharField(default='Рабочее место', max_length=200, verbose_name='Место (кабинет/здание)'),
        ),
    ]
