# Generated by Django 4.2.7 on 2026-04-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_workplace_computer_alter_workplace_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ups',
            name='battery_replaced_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата замены аккумулятора'),
        ),
        migrations.AddField(
            model_name='ups',
            name='battery_serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Серийный номер аккумулятора'),
        ),
    ]
