# Generated by Django 4.2.7 on 2026-04-25 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ups_battery_replaced_at_ups_battery_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название картриджа')),
                ('model', models.CharField(max_length=100, unique=True, verbose_name='Модель картриджа')),
                ('quantity_minsk', models.IntegerField(default=0, verbose_name='Количество в Минске')),
                ('quantity_machulishchi', models.IntegerField(default=0, verbose_name='Количество в Мачулищах')),
                ('compatible_mfps', models.ManyToManyField(blank=True, to='api.mfp', verbose_name='Совместимые МФУ')),
            ],
            options={
                'verbose_name': 'Картридж',
                'verbose_name_plural': 'Картриджи',
            },
        ),
        migrations.CreateModel(
            name='CartridgeMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Поступление'), ('out', 'Выдача'), ('transfer', 'Перемещение')], max_length=20, verbose_name='Тип операции')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('from_location', models.CharField(blank=True, choices=[('minsk', 'Минск'), ('machulishchi', 'Мачулищи')], max_length=20, null=True, verbose_name='Откуда')),
                ('to_location', models.CharField(blank=True, choices=[('minsk', 'Минск'), ('machulishchi', 'Мачулищи')], max_length=20, null=True, verbose_name='Куда')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('performed_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='Кто выполнил операцию')),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='api.cartridge', verbose_name='Картридж')),
            ],
            options={
                'verbose_name': 'Перемещение картриджа',
                'verbose_name_plural': 'Перемещения картриджей',
                'ordering': ['-created_at'],
            },
        ),
    ]
