# Generated by Django 4.2.7 on 2026-04-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cartridge_cartridgemovement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridge',
            name='name',
        ),
    ]
