# Generated by Django 4.2.7 on 2026-04-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_cartridge_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfp',
            name='cabinet_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер кабинета'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='login',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Логин'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='mac_address',
            field=models.CharField(blank=True, help_text='Формат: XX:XX:XX:XX:XX:XX', max_length=17, null=True, verbose_name='MAC адрес'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Пароль'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Серийный номер'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='status',
            field=models.CharField(choices=[('operational', '✅ В эксплуатации'), ('write_off', '📦 На списание')], default='operational', max_length=20, verbose_name='Статус'),
        ),
    ]
