# Generated by Django 4.2.7 on 2026-04-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Подтвержден администратором'),
        ),
    ]
