# Generated by Django 4.2.7 on 2026-04-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_userprofile_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ups',
            options={'verbose_name': 'Бесперебойник', 'verbose_name_plural': 'Бесперебойники'},
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Отдел'),
        ),
    ]
